export const GET_VIEWALLREPORT_STARTED = "GET_VIEWALLREPORT_STARTED";
export const GET_VIEWALLREPORT_COMPLETED = "GET_VIEWALLREPORT_COMPLETED";
export const GET_VIEWALLREPORT_FAILED = "GET_VIEWALLREPORT_FAILED";



export const getViewAllReportList = () => {
  return {
    type: GET_VIEWALLREPORT_STARTED,
    
  };
};

